mariusz-ostoja-swierczynski/tech-controllers

tech.py
Issue improved with very simple filtering on zones. to be improved in case of other variations
=> improvement for unregistered zones

test_tech.py
Running test_tech.py gives
AttributeError: 'Tech' object has no attribute 'module_data'
=> AttributeError

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Add issue templates for better issue reporting experience and data gathering.
=> 🚸 Add issue forms

custom_components/tech/translations/sk.json
Slovak localizations for tech controllers integration
=> feat - Slovak translation

custom_components/tech/sensor.py
Signal strength icon is now dependent on signal strength value.
Implements #68
=> :sparkles: Add changing signal strength icon

custom_components/tech/climate.py
closing https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/71
This will allow to setup a temperature by each 0,1 Celcius degree (previously default was 0,5 degree)
=> add target_temperature_step

README.md
Adding my working device which I tested and using in my apartment.
=> add working device

README.md
adding openAPI specification link to Readme
=> adding openapi specification link to tech controllers

custom_components/tech/sensor.py
Closes https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/76
Devices view: 
device view:
entities:
=> extend tile temp sensor

custom_components/tech/tech.py
close https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/33
=> fix bug-33

custom_components/tech/climate.py, custom_components/tech/config_flow.py, custom_components/tech/sensor.py, ruff.toml
Update ruff config and fix some linting issues
=> update ruff config and fix some linting issues

custom_components/tech/config_flow.py, custom_components/tech/strings.json, custom_components/tech/translations/en.json, custom_components/tech/translations/pl.json, custom_components/tech/translations/sk.json
=> :bug: Improve error conditions in config flow. Fixes #84

.github/workflows/tests.yml, .vscode/settings.json, requirements_test_api.txt, scripts/setup, scripts/test
changes for better test setup:
- we also installing all requirements for tests during `setup` of dev container, as PIP is arleady invoked those few adidtionall installs doesnt increse time of building devcontianer too much
- added script `scripts/test` for manual invoking test suite (dependencies are installed during `setup` script
- added VS code config for testing:
=> better testing setup

custom_components/tech/const.py, custom_components/tech/sensor.py, custom_components/tech/strings.json, custom_components/tech/translations/en.json, custom_components/tech/translations/pl.json, custom_components/tech/translations/sk.json
Adds support for window sensors. They are added as diagnostic entities under their zones (devices).
Battery and signal strength for the windows sensors are added as entity attributes.
Overall, they function very much like previously added actuator sensors.
Closes #94
=> ✨  Add support for window sensors

custom_components/tech/__init__.py, custom_components/tech/config_flow.py, requirements.txt, requirements_test_api.txt
solves:
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/99
https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/100
I have tested this multiple times by adding and removing controllers in different orders and combinations
=> 🐛 fix deprecation notice and multiple controllers handling

custom_components/tech/__init__.py, custom_components/tech/assets.py, custom_components/tech/climate.py, custom_components/tech/config_flow.py, custom_components/tech/tech.py, requirements.txt, requirements_test.txt, requirements_test_api.txt, tests/tests_api/test_api.py
Some minor improvments in areas of:
- redacting log (rewritten function)
- checking inputs
- some doc comments update
- fixed some linters reported issues
- requirements update
=> some minor code improvments

.github/ISSUE_TEMPLATE/bug_report.yml
Fix wrong link to contribution guide
=> :bug: Fix wrong link in bug report

custom_components/tech/__init__.py, custom_components/tech/assets.py, custom_components/tech/binary_sensor.py, custom_components/tech/climate.py, custom_components/tech/config_flow.py, custom_components/tech/const.py, custom_components/tech/coordinator.py, custom_components/tech/entity.py, custom_components/tech/sensor.py, custom_components/tech/tech.py, tests/tests_api/test_api.py
Satisfy Ruff and Pylint, which includes also extracting Coordinator to a separate module.
=> 🚨 Satisfy Ruff and Pylint

custom_components/tech/config_flow.py, hacs.json, requirements.txt, requirements_test.txt, requirements_test_api.txt, ruff.toml, tests/tests_api/__init__.py
bump dependencies and closing https://github.com/mariusz-ostoja-swierczynski/tech-controllers/issues/127
Ruff upgrade required changes in config https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#breaking-changes
this upgrade is not the best as it is causing also than version earlier HA than 2024.10 has also bug with adding multiple controllers at once
=> Bump dependencies

custom_components/tech/const.py, custom_components/tech/sensor.py
This pull request adds initial support for OpenTherm protocol.
=> Add initial support for OpenTherm.

README.md
Hi, thank you for creating and maintaining this repository. I successfully connected my L-12 to HA yesterday without any issues and can confirm that everything is functioning as expected
https://www.techsterowniki.pl/p/l-12
=> Add support for L-12 in README.md

.pre-commit-config.yaml, README.md, custom_components/tech/const.py, custom_components/tech/sensor.py, custom_components/tech/tech.py, tests/tests_api/__init__.py
Some minor changes:
- update precommit config versions
- run ruff linting on code
- simplified Readme:
- removed plan section as it is not accurate
- merged lists with working controllers
-  update instruction for manual installation
=> ✨ minor changes like linting, tooling and Readme

.envrc, .gitignore, CONTRIBUTING.md, devenv.lock, devenv.nix, devenv.yaml
Add an option to use nix devenv as development environment for the integration.
=> Add nix devenv
